// This file is automatically generated. Do not edit it directly.
//
// ⚠️ ATENÇÃO — DOIS CLIENTES SUPABASE COEXISTEM NESTE PROJETO:
//
// 1) ESTE arquivo (`@/integrations/supabase/client`) → cliente do LOVABLE CLOUD.
//    Usado APENAS para autenticação de usuários do app (ex.: `src/hooks/useAuth.tsx`).
//    URL/keys vêm de VITE_SUPABASE_* (gerenciadas pelo Lovable Cloud).
//
// 2) `@/services/supabase/client` → cliente do SUPABASE EXTERNO (projeto `sport_stats_hub`).
//    De onde vêm TODOS os dados do app: jogos, times, stats, apostas sugeridas, RPCs, views.
//    É o cliente usado pelas camadas `services/api/*` e `services/domain/*`.
//
// Regra prática: autenticação = este arquivo; dados de negócio = services/supabase/client.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});